BASE_URL = "https://www.xtrim.com.ec/"
CONTACTO_URL = f"{BASE_URL}contactanos/"
PAGAR_URL = "https://pagos.xtrim.com.ec/"
ZAPPING_URL = f"{BASE_URL}zapping/"
ZAPPING_UPGRADE_URL = "https://zappingsva.xtrim.com.ec/upgrade/login"
